### ISSUE TITLE
Component getter/setters have wrong class type

### ISSUE THREAD

**Issue by 2306781M** [oranellis/openSatCon#4]
using 'this.Value' gives error "expression must have class type but it has type "Component *"

**Comment by oranellis** [comment]
the `this` keyword is a pointer to the current object so to call a method or access a member of the class you would do this->doSomething() or this->Value, but for setters and getters you should just use the class variable Value as the value to return or write to. I might have made a mistake using `this` before, sorry I was probably still in Java mode
